# Generated by Django 5.1.3 on 2024-12-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남자"), ("F", "여자"), ("N", "비공개")],
                default="N",
                max_length=1,
            ),
        ),
    ]
